// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cplbplkhyqzqeziwycfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwbGJwbGtoeXF6cWV6aXd5Y2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNTU0MDYsImV4cCI6MjA2MzYzMTQwNn0.VjfRmZa6-dPyutwvueyommiMiqKZDKSDORz0xuPexho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);